# Generated by Django 3.1.6 on 2021-02-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210205_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='plan_date',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='plan_time',
        ),
        migrations.AddField(
            model_name='plan',
            name='plan_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
