# Generated by Django 3.1.6 on 2021-02-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_planjoiningrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="planjoiningrequest",
            name="response_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
