# Generated by Django 3.1.6 on 2021-03-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_planjoiningrequest_response_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='instagram_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
