# Generated by Django 3.1.6 on 2021-04-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_user_instagram_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images', verbose_name='CategoryImages'),
        ),
    ]
