# Generated by Django 3.1.6 on 2021-05-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210414_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='latitude',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='longitude',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
    ]
