# Generated by Django 3.1.6 on 2021-05-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210521_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
