# Generated by Django 3.1.6 on 2021-05-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210524_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='share_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
