# Generated by Django 3.1.6 on 2021-06-24 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_plan_share_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_link',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
